import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import RegisterForm from '@/components/RegisterForm/RegisterForm'
import LoginForm from '@/components/LoginForm/LoginForm'

export default function Login() {
  return (
    <>
      <Head>
        <title>Авторизация и регистрация</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Добро пожаловать в сситему. страница логина и регистрации</h1>
        <RegisterForm></RegisterForm>
        <LoginForm></LoginForm>
      </main>
    </>
  )
}
